version: 2

project_name: gohabitica

release:
  disable: false

builds:
  - id: gohabitica
    main: ./cmd/gohabitica
    binary: gohabitica
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

changelog:
  disable: true

